name: CI

on:
  pull_request:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  format:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn

      - name: Formatting
        run: yarn format-check

  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install Dependencies
        run: yarn

      - name: Linting
        run: yarn lint-check
