name: docs

on:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: retypeapp/actions-build@v2
        with:
          config: docs

      - uses: retypeapp/action-github-pages@v2
        with:
          branch: retype
          update-branch: true
