name: publish

on:
  push:
    tags:
      - v*

jobs:
  address-parser:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: yarn --ignore-scripts

      - name: Build
        run: yarn build
        working-directory: tools/address-parser

      - name: Publish
        run: npm publish
        working-directory: tools/address-parser
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
  docs:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: retypeapp/action-build@v2
        with:
          config: docs

      - uses: retypeapp/action-github-pages@v2
        with:
          branch: retype
          update-branch: true
